name: 'student_performance'
version: '1.0.0'
config-version: 2

profile: 'student_performance'

model-paths: ["student_dbt/models"]
analysis-paths: ["student_dbt/analyses"]

models:
  example:
    staging:
      +materialized: view
      +schema: staging
    dimensions:
      +materialized: table
      +schema: dimensions
    facts:
      +materialized: table
      +schema: facts
