student_performance:
  target: dev
  outputs:
    dev:
      type: duckdb
      # استخدم مسار DB صحيح في مشروعك (لاحظ الشرطية للـ Backslash أو استخدم /)
      path: "E:/New folder/Student-Performance-Dashboar-/student_performance.duckdb"
      schema: analytics